#!/bin/sh

get_key() {
	stty raw -echo
	char=$(dd bs=1 count=1 2>/dev/null)
	stty -raw echo
	printf '%s' "$char"
}

menu_choice=""
menu(){
	list="$1"
	prompt="$2"
	last="A"
	pos=0

	while [ 1 ]; do
		clear
		i=0;

		# Draw the menu
		while read line; do
			if [ $i -eq $((pos % $(echo "$list" | wc -l))) ]; then
				printf "\033[32m>$line\033[0m\n"
				if [ "$last" = $'\n' ] || [ "$last" = $'\r' ]; then
					menu_choice="$line"
					return 0;
				fi
			else printf "$line\n"; fi
			i=$((i+1))
done <<EOF
$list
EOF
		# Handle arrow keys
		last=$(get_key)
		[ "$last" = "A" ] && pos=$((pos-1));
		[ "$last" = "B" ] && pos=$((pos+1));
	done
}

DEMO_FOLDER="shapes/"
menu "$(find $DEMO_FOLDER | tail -n+2 )" "Select a shape file"
clear

# Generate temp file including the selected file
tmp=$(mktemp --suffix=".c")
echo "#include \"$menu_choice\"" > "$tmp"
cat render.c >> "$tmp"
mv "$tmp" .tmp.c

# Compile and run
gcc ".tmp.c"
./a.out
rm "$tmp" .tmp.c
