#!/bin/sh

menu_choice=""
function menu(){
	local list="$1"
	local prompt="$2"
	
	code=-1
	last="A"
	pos=0

	while [ 1 ]; do
		clear
		i=0;

		# Draw the menu
		while read line; do
			if [ $i -eq $((pos % $(echo "$list" | wc -l))) ]; then
				echo -e "\033[32m>$line\033[0m"

				if [ $(printf '%d' "'$last") -eq 0 ]; then
					menu_choice="$line"
					return 0;
				fi
			else echo "$line"; fi

			# Enter pressed

			# Handle arrow keys
			i=$((i+1))
done <<EOF
$list
EOF
		read -n 1 -s -r last
		[ "$last" = "A" ] && pos=$((pos-1));
		[ "$last" = "B" ] && pos=$((pos+1));
	done
}

DEMO_FOLDER="shapes/"
menu "$(find $DEMO_FOLDER | tail -n+2 )" "Select a shape file"
clear

# Generate temp file including the selected file
tmp=$(mktemp --suffix=".c")
echo "#include \"$menu_choice\"" > "$tmp"
cat render.c >> "$tmp"
mv "$tmp" .tmp.c

# Compile and run
gcc ".tmp.c"
./a.out
rm "$tmp" .tmp.c
